[package]
name = "trading-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "20.5.0", features = ["contract"] }
soroban-sdk-contract-meta = "20.5.0"

[dev-dependencies]
soroban-sdk = { version = "20.5.0", features = ["contract"] }
